export type ResendEmailInput = {
  to: string;
  subject: string;
  html: string;
  text?: string;
  idempotencyKey?: string;
};

export type ResendEmailResult = {
  delivered: boolean;
  id?: string;
  destination: "resend";
  status: number;
};

export class EmailConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EmailConfigError";
  }
}

export class EmailSendError extends Error {
  constructor(
    message: string,
    public status: number,
    public details?: unknown,
  ) {
    super(message);
    this.name = "EmailSendError";
  }
}

const defaultTestRecipient = "delivered@resend.dev";

function getEnvValue(env: Record<string, string | undefined>, key: string) {
  const value = env[key]?.trim();
  return value && value.length > 0 ? value : undefined;
}

export function isEmailAddress(value: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

export function formatResendFrom(fromEmail: string) {
  if (fromEmail.includes("<")) return fromEmail;
  return `Private Lab Test <${fromEmail}>`;
}

export function getResendConfigStatus(env: Record<string, string | undefined> = process.env) {
  const apiKey = getEnvValue(env, "RESEND_API_KEY");
  const fromEmail = getEnvValue(env, "RESEND_FROM_EMAIL");
  const testRecipient = getEnvValue(env, "RESEND_TEST_RECIPIENT");

  return {
    configured: Boolean(apiKey && fromEmail),
    hasApiKey: Boolean(apiKey),
    hasFromEmail: Boolean(fromEmail),
    fromEmail: fromEmail ? formatResendFrom(fromEmail) : undefined,
    testRecipient: testRecipient && isEmailAddress(testRecipient) ? testRecipient : defaultTestRecipient,
  };
}

export function resolveEmailTestRecipient(requestedRecipient?: string, env: Record<string, string | undefined> = process.env) {
  const configuredRecipient = getEnvValue(env, "RESEND_TEST_RECIPIENT");

  if (configuredRecipient && isEmailAddress(configuredRecipient)) {
    return configuredRecipient;
  }

  if (env.EMAIL_TEST_ALLOW_CUSTOM_TO === "enabled" && requestedRecipient && isEmailAddress(requestedRecipient)) {
    return requestedRecipient;
  }

  return defaultTestRecipient;
}

export function buildResendTestEmail(to: string) {
  const timestamp = new Date().toISOString();

  return {
    to,
    subject: "Private Lab Test email check",
    text: `Private Lab Test email delivery check at ${timestamp}. No patient or lab result data is included.`,
    html: `
      <div style="font-family:Arial,sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#10231f;">
        <p style="font-size:12px;letter-spacing:0.12em;text-transform:uppercase;color:#32796f;font-weight:700;">Private Lab Test</p>
        <h1 style="font-size:24px;line-height:1.25;margin:0 0 12px;">Email delivery check</h1>
        <p style="font-size:15px;line-height:1.6;margin:0 0 16px;">Resend is connected and this transactional email test was generated by the Private Lab Test app.</p>
        <p style="font-size:13px;line-height:1.6;color:#5a6f6a;margin:0;">No patient information, lab order data, or result values are included in this message.</p>
        <p style="font-size:12px;line-height:1.6;color:#7a8c88;margin-top:24px;">Sent at ${timestamp}</p>
      </div>
    `,
    idempotencyKey: `private-lab-test-resend-check-${timestamp.slice(0, 13)}`,
  };
}

export async function sendResendEmail(
  input: ResendEmailInput,
  env: Record<string, string | undefined> = process.env,
  fetcher: typeof fetch = fetch,
): Promise<ResendEmailResult> {
  const apiKey = getEnvValue(env, "RESEND_API_KEY");
  const fromEmail = getEnvValue(env, "RESEND_FROM_EMAIL");

  if (!apiKey) {
    throw new EmailConfigError("RESEND_API_KEY is not configured.");
  }

  if (!fromEmail) {
    throw new EmailConfigError("RESEND_FROM_EMAIL is not configured.");
  }

  const response = await fetcher("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
      ...(input.idempotencyKey ? { "Idempotency-Key": input.idempotencyKey } : {}),
    },
    body: JSON.stringify({
      from: formatResendFrom(fromEmail),
      to: input.to,
      subject: input.subject,
      html: input.html,
      text: input.text,
    }),
  });
  const body = (await response.json().catch(() => ({}))) as { id?: string; message?: string; error?: { message?: string } };

  if (!response.ok) {
    throw new EmailSendError(body.error?.message || body.message || "Resend email send failed.", response.status, body);
  }

  return {
    delivered: true,
    id: body.id,
    destination: "resend",
    status: response.status,
  };
}
